### ISSUE TITLE
Chunk counts are screwed up

### ISSUE THREAD

**Issue by GGEZLOLLLLLLLLLLLLLLLLXD** [froobynooby/ViewDistanceTweaks#6]
At a view distance of 10 with 1 player online, `/vdt status` shows 1764 loaded chunks, but it should be (10*2+1)^2=441 chunks. 1764 chunks is a 42x42 box instead of 21x21.

**Comment by froobynooby** [comment]
Could you share a copy of your config?

**Comment by GGEZLOLLLLLLLLLLLLLLLLXD** [comment]
(comments cut)
```
version: 2

enabled: true

adjustment-mode: reactive

proactive-mode-settings:
  global-chunk-count-target: 2150

reactive-mode-settings:
  increase-tps-threshold: 19.5
  decrease-tps-threshold: 16.0

  tps-tracker-settings:
    collection-period: 1200
    trim-outliers-to-within: 95.0

  tps-prediction:
    enabled: true
    history-length: 20

ticks-per-check: 1200

passed-checks-for-increase: 3

passed-checks-for-decrease: 1

log-view-distance-changes: true

world-settings:
  default:
    minimum-view-distance: 7
    maximum-view-distance: 11
    chunk-weight: 4.0
    chunk-counter-settings:
      exclude-overlap: true

    world:
        chunk-weight: 4.0

    world_nether:
        chunk-weight: 5.0

    world_the_end:
        chunk-weight: 3.0

paper-settings:
  no-tick-view-distance:
    enabled: true

    global-chunk-count-target: 4003

  world-settings:
    default:
      minimum-no-tick-view-distance: 12
      maximum-no-tick-view-distance: 15
```

A few more questions: Can the notickviewdistance exceed 15 (normal can't)? If the client-side view distance is less, does this mean the server also loads less chunks?
